import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Renox Omache</title>
        <meta name="description" content="Generated by Renox Omache" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Renox Omache"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width:768px) 100vw,
              (max-width:1200px) 50vw,
              50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Transforming Ideas into Digital Reality"
                className="!text-5xl !text-left
              xl:!text-5xl lg:!text-center   lg:!text=6xl md:!text-5xl sm:!text-3xl
              "
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Step into the realm of my portfolio, where the magic of
                creativity intertwines with the wizardry of cutting-edge
                technology. As a fervent developer, I traverse the realms of
                Front End, Back End, and the captivating world of Machine
                Learning. Join me on this exhilarating journey as we conquer
                challenges and weave elegant solutions. Embark on an exploration
                of my work, where ideas come to life and user experiences
                transcend the ordinary, leaving an indelible mark on the digital
                landscape of today.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6
              rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
              border-2 border-solid border-transparent hover:border-dark
              dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
              hover:dark:border-light md:p-2 md:px-4 md:text-base
              "
                >
                  Resume
                </Link>
                <a
                  href="mailto:omacherenox@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </a>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
//FINAL
